In [1]:
import sys; sys.path.append("../../..")
from notebook_imports import *
display(HTML("<style>.container { width:90% !important; }</style>"))
pd.set_option("display.max_rows", 999)
pd.get_option("display.max_rows")

999

In [2]:
# !pip install calmap
import numpy as np
import pandas as pd


In [3]:
x = np.nan * np.zeros((3, 7))
x = np.ones((3,3))
x[0,0] = 1
x[0,1] = 2
x[0,2] = 3
x[1,0] = 1
x[1,1] = 2
x[1,2] = 3
x[2,0] = 1
x[2,1] = 2
x[2,2] = 3
x[[1,2],[1]]

array([2., 2.])

In [8]:
x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [9]:
x[[1,2],[1]]
# This selects colum 1 in rows 1 and 2

array([2., 2.])

In [10]:
x[[0,2],[1]]
# This selects (0,1) and (2,1)

array([2., 2.])

In [11]:
print(x[[1,2],[1,0]])
# This selects (1,1) and (2,0)

[2. 1.]


In [12]:
# Thus x[arrayA,arrayB] = arrayC
# will set all the tuples of zip(arrayA, arrayB)
# note: arrayA and B need to be of the same size, additionally so does array c ...